const SERVICE_AREA_GROUPS = [
  {
    county: "Iredell County",
    homeAreas: ["statesville", "mooresville", "troutman"],
    areas: [
      { slug: "statesville", name: "Statesville" },
      { slug: "mooresville", name: "Mooresville" },
      { slug: "troutman", name: "Troutman" },
      { slug: "harmony", name: "Harmony" },
      { slug: "love-valley", name: "Love Valley" },
      { slug: "davidson", name: "Davidson" },
    ],
  },
  {
    county: "Mecklenburg County",
    homeAreas: ["charlotte", "cornelius", "huntersville", "matthews"],
    areas: [
      { slug: "charlotte", name: "Charlotte" },
      { slug: "cornelius", name: "Cornelius" },
      { slug: "davidson", name: "Davidson" },
      { slug: "huntersville", name: "Huntersville" },
      { slug: "matthews", name: "Matthews" },
      { slug: "mint-hill", name: "Mint Hill" },
      { slug: "pineville", name: "Pineville" },
      { slug: "stallings", name: "Stallings" },
    ],
  },
  {
    county: "Gaston County",
    homeAreas: ["gastonia", "belmont", "kings-mountain", "mount-holly"],
    areas: [
      { slug: "gastonia", name: "Gastonia" },
      { slug: "belmont", name: "Belmont" },
      { slug: "bessemer-city", name: "Bessemer City" },
      { slug: "cherryville", name: "Cherryville" },
      { slug: "cramerton", name: "Cramerton" },
      { slug: "dallas", name: "Dallas" },
      { slug: "high-shoals", name: "High Shoals" },
      { slug: "kings-mountain", name: "Kings Mountain" },
      { slug: "lowell", name: "Lowell" },
      { slug: "mcadenville", name: "McAdenville" },
      { slug: "mount-holly", name: "Mount Holly" },
      { slug: "ranlo", name: "Ranlo" },
      { slug: "stanley", name: "Stanley" },
    ],
  },
  {
    county: "Lincoln County",
    homeAreas: ["lincolnton", "denver"],
    areas: [
      { slug: "lincolnton", name: "Lincolnton" },
      { slug: "denver", name: "Denver" },
      { slug: "iron-station", name: "Iron Station" },
      { slug: "lowesville", name: "Lowesville" },
      { slug: "westport", name: "Westport" },
      { slug: "crouse", name: "Crouse" },
      { slug: "maiden", name: "Maiden" },
    ],
  },
  {
    county: "Rowan County",
    homeAreas: ["salisbury", "kannapolis"],
    areas: [
      { slug: "salisbury", name: "Salisbury" },
      { slug: "kannapolis", name: "Kannapolis" },
      { slug: "china-grove", name: "China Grove" },
      { slug: "cleveland", name: "Cleveland" },
      { slug: "east-spencer", name: "East Spencer" },
      { slug: "faith", name: "Faith" },
      { slug: "gold-hill", name: "Gold Hill" },
      { slug: "granite-quarry", name: "Granite Quarry" },
      { slug: "landis", name: "Landis" },
      { slug: "rockwell", name: "Rockwell" },
      { slug: "spencer", name: "Spencer" },
    ],
  },
  {
    county: "Cabarrus County",
    homeAreas: ["concord", "kannapolis", "harrisburg"],
    areas: [
      { slug: "concord", name: "Concord" },
      { slug: "kannapolis", name: "Kannapolis" },
      { slug: "harrisburg", name: "Harrisburg" },
      { slug: "mount-pleasant", name: "Mount Pleasant" },
      { slug: "midland", name: "Midland" },
      { slug: "locust", name: "Locust" },
    ],
  },
  {
    county: "Catawba County",
    homeAreas: ["hickory", "newton", "conover"],
    areas: [
      { slug: "hickory", name: "Hickory" },
      { slug: "newton", name: "Newton" },
      { slug: "conover", name: "Conover" },
      { slug: "long-view", name: "Long View" },
      { slug: "maiden", name: "Maiden" },
      { slug: "claremont", name: "Claremont" },
      { slug: "catawba", name: "Catawba" },
      { slug: "brookford", name: "Brookford" },
    ],
  },
];

const CONFIG = {
  businessName: "A&W Fencing",
  niche: "Fencing",
  tagline: "Professional Fencing Installations Built for Lasting Performance",
  phone: "(704) 741-8528",
  phoneRaw: "7047418528",
  email: "",
  city: "Cherryville",
  primaryMarket: "Charlotte",
  siteUrl: "https://aw-fencing.com",
  state: "North Carolina",
  stateShort: "NC",
  address: "Cherryville, NC 28021",
  licenseNumber: "",
  colors: { primary: "#3B82F6", secondary: "#1C2333" },
  social: {
    facebook: "https://www.facebook.com/profile.php?id=61591272494485",
    instagram: "https://www.instagram.com/aw.fence/",
    googleBusinessProfile: "https://share.google/aMcOY1YjUOyQJ4O16",
  },
  googleReviewsUrl: "",
  rating: "",
  reviewCount: 0,
  yearsExperience: 0,
  projectsCompleted: "",
  satisfactionRate: "",
  webhookUrl: "https://hook.us2.make.com/bo7e27fc6zgfm0kt35rhxtxqs7o1udtm",
  metaPixelId: "",
  maps: { mapEmbedUrl: "", mapSearchQuery: "A&W Fencing Cherryville NC", mapHeight: 420 },
  hero: {
    eyebrow: "Local Home Service Professionals",
    headline: "Fence Installation in Charlotte & Surrounding Communities",
    subheadline: "Residential, commercial, and agricultural fences and custom gates planned for your property's layout and purpose.",
    ctaPrimary: "Get Free Estimate",
    ctaSecondary: "Explore Services",
    heroImage: "/public/hero/clean-wood-privacy-fence.jpg",
  },
  services: [
    {
      slug: "residential-fence-installation",
      name: "Residential Fence Installation",
      desc: "Privacy, security, and curb appeal tailored to your home's specific needs and layout.",
      longDesc: "Enhance your home's privacy, security, and curb appeal with a professionally installed residential fence. We offer a variety of materials and styles, including wood, vinyl, aluminum, and chain link, designed to complement your property's aesthetic and meet your specific needs for pet containment, child safety, or boundary definition. Our team ensures a seamless installation process from start to finish.",
      benefits: ["Enhanced Privacy", "Defined Property Boundaries", "Improved Curb Appeal", "Pet Containment", "Material and Gate Options"],
      faqs: [
        { q: "What types of residential fences do you install?", a: "We install a wide range of residential fences, including wood privacy fences, decorative aluminum fences, low-maintenance vinyl fences, and durable chain link fences." },
        { q: "How long does residential fence installation take?", a: "Timing depends on the length, material, gates, site conditions, weather, and any approvals. We discuss a project-specific timeline after reviewing the property." },
        { q: "Do I need approval for a residential fence in Charlotte?", a: "Requirements depend on the parcel and fence location. Charlotte requires a no-cost fence and wall certificate for fences along city-maintained streets or sidewalks. Check the applicable local rules and any HOA requirements before work begins." }
      ],
      image: "/public/projects/wood-privacy-fence-gate.jpg",
      imageAlt: "Wood privacy fence and gate on a residential property",
    },
    {
      slug: "commercial-fence-installation",
      name: "Commercial Fence Installation",
      desc: "Professional-grade perimeter solutions designed to protect business properties and assets effectively.",
      longDesc: "Protect your business assets and secure your commercial property with our professional-grade fencing solutions. We design and install durable fences for various commercial needs, including perimeter security, access control, and aesthetic enhancement. Our options include heavy-duty chain link, ornamental iron, anti-climb fencing, and more, all built to withstand demanding environments and provide lasting security.",
      benefits: ["Asset Protection & Security", "Deterrence of Trespassing", "Controlled Access Points", "Enhanced Business Image", "Compliance with Regulations"],
      faqs: [
        { q: "What access features can a commercial fence include?", a: "Depending on the site, the design may include reinforced gates, controlled entry, and appropriate fence materials. The team reviews traffic and security requirements before recommending a system." },
        { q: "Can you discuss a larger commercial fence project?", a: "Yes. Share the site address, perimeter, access points, and security needs so the team can assess the scope and confirm availability." },
        { q: "What materials are best for commercial security fences?", a: "Heavy-gauge chain link, ornamental steel/iron, and high-security mesh are popular choices for their durability and security features." }
      ],
      image: "/public/services/commercial-perimeter-fence.jpg",
      imageAlt: "Illustrative chain-link fence and gate at a commercial property",
    },
    {
      slug: "custom-gates-access-control",
      name: "Custom Gates & Automatic Access Control",
      desc: "Secure entry systems engineered for convenience and controlled access on any property type.",
      longDesc: "Enhance the convenience and security of your property with custom gates and state-of-the-art automatic access control systems. Whether you need a grand entrance gate for your estate, a secure entry for a commercial complex, or a simple automated driveway gate, we design and install solutions that combine functionality, durability, and aesthetic appeal. Our systems can include keypads, remote controls, intercoms, and smart integration.",
      benefits: ["Convenient Property Access", "Enhanced Security & Control", "Increased Property Value", "Custom Design Options", "Integration with Smart Systems"],
      faqs: [
        { q: "What types of automatic gates do you install?", a: "Swing and slide gates are among the options. The opening width, slope, available clearance, and intended use determine which design fits." },
        { q: "What access controls can a gate include?", a: "Depending on the selected equipment, options can include remotes, keypads, card readers, smartphone controls, and safety sensors." },
        { q: "What happens if there's a power outage?", a: "Some gate operators offer battery backup or a manual release. Confirm the exact operation and backup capability for the proposed system." }
      ],
      image: "/public/services/custom-driveway-gate.jpg",
      imageAlt: "Illustrative driveway gate with a keypad entry point",
    },
    {
      slug: "farm-agricultural-fencing",
      name: "Farm & Agricultural Fencing",
      desc: "Reliable containment and protection for livestock, crops, and rural property boundaries.",
      longDesc: "Provide reliable containment and protection for your livestock, crops, and rural property boundaries with our specialized farm and agricultural fencing solutions. We understand the unique needs of agricultural properties and offer robust options like woven wire, high-tensile wire, barbed wire, and post-and-rail fences, designed for durability and effectiveness in managing animals and defining large land parcels.",
      benefits: ["Effective Livestock Containment", "Crop Protection from Wildlife", "Clear Boundary Definition", "Durable & Long-lasting", "Reduced Maintenance"],
      faqs: [
        { q: "What is the best fence for livestock containment?", a: "The best fence depends on the type of livestock. Woven wire is excellent for smaller animals, while high-tensile and barbed wire are effective for larger animals like cattle." },
        { q: "Can you assess fencing for larger acreage?", a: "Yes. Share the property address, approximate acreage, livestock type, and required gates so the team can assess the layout and confirm the scope." },
        { q: "Do you offer repair services for farm fences?", a: "Absolutely. We provide repair services to maintain the integrity and functionality of your existing farm and agricultural fences." }
      ],
      image: "/public/services/farm-woven-wire-fence.jpg",
      imageAlt: "Illustrative woven-wire fence and field gate on rural land",
    },
  ],
  serviceAreaGroups: SERVICE_AREA_GROUPS,
  serviceAreas: Array.from(new Map(
    SERVICE_AREA_GROUPS.flatMap(group => group.areas.map(area => [area.slug, area]))
  ).values()).map(area => ({
    ...area,
    counties: SERVICE_AREA_GROUPS.filter(group => group.areas.some(item => item.slug === area.slug)).map(group => group.county),
  })),
  testimonials: [],
  processSteps: [
    { title: "Tell Us About Your Project", desc: "Share your goals and schedule a convenient consultation." },
    { title: "Receive a Clear Plan", desc: "We assess the work and provide a straightforward recommendation." },
    { title: "Professional Service", desc: "Our team completes the job with care and clear communication." },
    { title: "Final Walkthrough", desc: "We make sure the completed work meets your expectations." },
  ],
  faqs: [
    { q: "What areas do you serve?", a: "We serve Charlotte and surrounding communities across Mecklenburg, Gaston, Lincoln, Rowan, Cabarrus, Catawba, and Iredell counties. Our business is based in Cherryville, NC. Contact us with your project address to confirm availability." },
    { q: "What types of fencing materials do you offer?", a: "We offer a wide range of materials including durable wood, low-maintenance vinyl, elegant aluminum, and robust chain link, as well as specialized options for agricultural and custom gate projects." },
    { q: "How long does a typical fence installation take?", a: "The timeline for installation varies depending on the size, complexity, and materials chosen for your project. We provide an estimated timeline during your initial consultation." },
    { q: "Do you offer financing options for fencing projects?", a: "Yes, we understand that a new fence is an investment. Financing options are available through First Citizens Bank to help make your project more affordable." },
    { q: "How do I get a free estimate?", a: "Getting a free estimate is easy! Simply contact us by phone or through our website, and we'll schedule a convenient time to discuss your project and provide a personalized quote." },
    { q: "Are your fences guaranteed?", a: "We stand by the quality of our work and materials. Our installations are backed by skilled craftsmanship and a commitment to lasting performance." },
    { q: "Do you handle fence repairs?", a: "While our primary focus is new installations, we can often assist with repairs for fences we've installed or significant repair projects. Please contact us to discuss your specific needs." },
    { q: "What is the best fence for privacy?", a: "For maximum privacy, a solid wood privacy fence or a vinyl privacy fence is generally recommended. Both offer excellent visual obstruction and can be customized to your desired height and style." }
  ],
  portfolioProjects: [],
  legal: { privacyPolicyDate: "May 1, 2025", termsDate: "May 1, 2025" },
};
